Cosmetica but make it fabri-quilt and 1.18.2
EyezahMC/Cosmetica pull request #32
Opened 2022-04-29 17:54 UTC by craftish37

Men uses Fabric, poggers uses Quilt, gods uses Quilt & Cosmetica
This PR is here in order to create gods as well 🥵

2022-04-29 22:04 UTC, valoeghese requested changes
You seem to have an old version of the codebase?

2022-04-29 22:04 UTC, valoeghese commented on src/main/java/com/eyezah/cosmetics/AuthlibMixinEnabler.java
> +}
we already fixed the quilt issue by just deleting this entire class

2022-04-29 22:04 UTC, valoeghese commented on gradle.properties
> +minecraft_version=1.18.2
master should already be on 1.18.2? what?

2022-04-29 22:04 UTC, valoeghese commented on src/main/java/com/eyezah/cosmetics/CosmeticaConfig.java
> +        if (!parentDir.exists()) parentDir.mkdir();
I thought this code already existed?

2022-04-29 22:04 UTC, valoeghese commented on src/main/java/com/eyezah/cosmetics/mixin/MixinClientLevel.java
> +		super(writableLevelData, resourceKey, (Holder<DimensionType>) dimensionType, supplier, bl, bl2, l);
again, how do you have the 1.18.1 code on 1.18.2

2022-04-29 22:06 UTC, valoeghese commented
Nvm I just realised I reverted an important commit and accidentally merged it into master

2022-04-29 22:13 UTC, valoeghese commented
Yeah if you can fix all the stuff I broke on master branch that'll be cool lmao
Please don't re-add the prelaunch entrypoint though

2022-04-29 22:15 UTC, craftish37 reviewed
LGTM (checking twice actually)

2022-04-30 02:30 UTC, valoeghese requested changes

2022-04-30 02:30 UTC, valoeghese commented on src/main/java/com/eyezah/cosmetics/AuthlibMixinEnabler.java
> +}
this class is still present. can you please not re-add it? it's a remnant from older tests

2022-04-30 02:31 UTC, valoeghese commented on src/main/java/com/eyezah/cosmetics/mixin/MixinClientLevel.java
> +		super(writableLevelData, resourceKey, (Holder<DimensionType>) dimensionType, supplier, bl, bl2, l);
also instead of casting here just change the parameter

2022-04-30 12:15 UTC, craftish37 commented
Looks good to me this time, lmk if I re-missed something 👨‍🦯

2022-04-30 21:12 UTC, valoeghese approved these changes

2022-04-30 21:12 UTC, merged